filebeat.inputs:
- type: log
  enabled: true
  paths:
      - /var/log/messages

output.logstash:
  hosts: ["logstash:5044"]

#xpack.monitoring:
#  enabled: true
#  elasticsearch:
#    hosts: ["http://10.10.1.224:9200"]