version: '2.2'
services:

  es-hot:
    image: murzinvit/es-hot:latest
    container_name: es-hot
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    depends_on:
      - es-warm

  es-warm:
    image: murzinvit/es-warm:latest
    container_name: es-warm
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elastic

  logstash:
    image: murzinvit/logstash:latest
    container_name: logstash
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - elastic
    depends_on:
      - es-hot
      - es-warm

  kibana:
    image: murzinvit/kibana:latest
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./data:/mnt
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
