---
 - src: git@github.com:murzinvit/python3-role.git
   scm: git
   version: 1.0.1
   name: python3-role

 - src: git@github.com:murzinvit/java-role.git
   scm: git
   version: "1.0.1"
   name: java-role

 - src: git@github.com:murzinvit/elastic-role.git
   scm: git
   version: "1.0.1"
   name: elastic-role

 - src: git@github.com:murzinvit/kibana-role.git
   scm: git
   version: "1.0.1"
   name: kibana-role

 - src: git@github.com:murzinvit/logstash-role.git
   scm: git
   version: "1.0.1"
   name: logstash-role

